//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF
{
    [DataContract(IsReference=true)]
    public partial class aspnet_Roles
    {
    	[Required]
        [DataMember]
        public System.Guid ApplicationId { get; set; }
    	[Required]
        [DataMember]
        public System.Guid RoleId { get; set; }
    	[StringLength(256)]
    	[Required]
        [DataMember]
        public string RoleName { get; set; }
    	[StringLength(256)]
    	[Required]
        [DataMember]
        public string LoweredRoleName { get; set; }
    	[StringLength(256)]
        [DataMember]
        public string Description { get; set; }
    }
    
}
