//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Data.Entity;


using Capstone.Infrastructure.Data.EF.Entities;

namespace Capstone.Infrastructure.Data.EF
{
    
    ///<sumary>
    ///Base contract for context in Main Module 
    ///</sumary>
    public interface IUnitOfWork 
    {
    	/// <summary>
        /// Creates an object set for a type
        /// </summary>
        /// <typeparam name="TEntity">Type of elements in object set</typeparam>
        /// <returns>Object set of type TEntity</returns>
        IDbSet<TEntity> CreateSet<TEntity>() where TEntity : class;
    
        /// <summary>
        /// Commits changes made to the container
        /// </summary>
        void Commit();
    
        /// <summary>
        /// Commits changes made to the container
        /// </summary>
        void CommitAndRefreshChanges();
    
        /// <summary>
        /// Rolls back changes not committed to the DB
        /// </summary>
        void RollbackChanges();
    
        void Attach<TEntity>(TEntity item) where TEntity : class;
    
        void SetModified<TEntity>(TEntity item) where TEntity : class;
    
        void ApplyCurrentValues<TEntity>(TEntity item) where TEntity : class;
       
        #region ObjectSet Properties
    
        IDbSet<aspnet_Applications> aspnet_Applications{ get; }
        
    
        IDbSet<aspnet_Membership> aspnet_Membership{ get; }
        
    
        IDbSet<aspnet_Paths> aspnet_Paths{ get; }
        
    
        IDbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers{ get; }
        
    
        IDbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser{ get; }
        
    
        IDbSet<aspnet_Profile> aspnet_Profile{ get; }
        
    
        IDbSet<aspnet_Roles> aspnet_Roles{ get; }
        
    
        IDbSet<aspnet_SchemaVersions> aspnet_SchemaVersions{ get; }
        
    
        IDbSet<aspnet_Users> aspnet_Users{ get; }
        
    
        IDbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events{ get; }
        
    
        IDbSet<Features_Bugs> Features_Bugs{ get; }
        
    
        IDbSet<PermissionCategory> PermissionCategories{ get; }
        
    
        IDbSet<Permission> Permissions{ get; }
        
    
        IDbSet<Project> Projects{ get; }
        
    
        IDbSet<ProjectBacklog> ProjectBacklogs{ get; }
        
    
        IDbSet<ReleaseBacklog> ReleaseBacklogs{ get; }
        
    
        IDbSet<Sprint> Sprints{ get; }
        
    
        IDbSet<sysdiagram> sysdiagrams{ get; }
        
    
        IDbSet<UserProjectPermission> UserProjectPermissions{ get; }
        

        #endregion

    
    	
    
    }
}
	
