//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF
{
    [DataContract(IsReference=true)]
    public partial class UserProfile
    {
        [DataMember]
        public int UserProfile_id { get; set; }
    	[Required]
        [DataMember]
        public System.Guid UserId { get; set; }
    	[StringLength(255)]
    	[RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*")]
    	[Required]
        [DataMember]
        public string EmailAddress { get; set; }
    	[StringLength(100)]
    	[Required]
        [DataMember]
        public string UserName { get; set; }
    	[StringLength(50)]
    	[Required]
        [DataMember]
        public string FirstName { get; set; }
    	[StringLength(50)]
    	[Required]
        [DataMember]
        public string LastName { get; set; }
    }
    
}
