//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class aspnet_Membership
    {
    	[Required]
        [DataMember]
        public System.Guid ApplicationId { get; set; }
    	[Required]
        [DataMember]
        public System.Guid UserId { get; set; }
    	[StringLength(128)]
    	[Required]
        [DataMember]
        public string Password { get; set; }
    	[Required]
        [DataMember]
        public int PasswordFormat { get; set; }
    	[StringLength(128)]
    	[Required]
        [DataMember]
        public string PasswordSalt { get; set; }
    	[StringLength(16)]
        [DataMember]
        public string MobilePIN { get; set; }
    	[StringLength(256)]
    	[RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*")]
        [DataMember]
        public string Email { get; set; }
    	[StringLength(256)]
    	[RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*")]
        [DataMember]
        public string LoweredEmail { get; set; }
    	[StringLength(256)]
        [DataMember]
        public string PasswordQuestion { get; set; }
    	[StringLength(128)]
        [DataMember]
        public string PasswordAnswer { get; set; }
    	[Required]
        [DataMember]
        public bool IsApproved { get; set; }
    	[Required]
        [DataMember]
        public bool IsLockedOut { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime CreateDate { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime LastLoginDate { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime LastPasswordChangedDate { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime LastLockoutDate { get; set; }
    	[Required]
        [DataMember]
        public int FailedPasswordAttemptCount { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    	[Required]
        [DataMember]
        public int FailedPasswordAnswerAttemptCount { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
    	[StringLength(8000)]
        [DataMember]
        public string Comment { get; set; }
    
        [DataMember]
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        [DataMember]
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
    
}
