//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
            this.UserProjectPermissions = new HashSet<UserProjectPermission>();
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
        }
    
    	[Required]
        [DataMember]
        public System.Guid ApplicationId { get; set; }
    	[Required]
        [DataMember]
        public System.Guid UserId { get; set; }
    	[StringLength(256)]
    	[Required]
        [DataMember]
        public string UserName { get; set; }
    	[StringLength(256)]
    	[Required]
        [DataMember]
        public string LoweredUserName { get; set; }
    	[StringLength(16)]
        [DataMember]
        public string MobileAlias { get; set; }
    	[Required]
        [DataMember]
        public bool IsAnonymous { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime LastActivityDate { get; set; }
    
        [DataMember]
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        [DataMember]
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        [DataMember]
        public virtual aspnet_Profile aspnet_Profile { get; set; }
        public virtual ICollection<UserProjectPermission> UserProjectPermissions { get; set; }
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
    }
    
}
