//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class aspnet_WebEvent_Events
    {
    	[StringLength(32)]
    	[Required]
        [DataMember]
        public string EventId { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime EventTimeUtc { get; set; }
    	[Required]
        [DataMember]
        public System.DateTime EventTime { get; set; }
    	[StringLength(256)]
    	[Required]
        [DataMember]
        public string EventType { get; set; }
    	[Required]
        [DataMember]
        public decimal EventSequence { get; set; }
    	[Required]
        [DataMember]
        public decimal EventOccurrence { get; set; }
    	[Required]
        [DataMember]
        public int EventCode { get; set; }
    	[Required]
        [DataMember]
        public int EventDetailCode { get; set; }
    	[StringLength(1024)]
        [DataMember]
        public string Message { get; set; }
    	[StringLength(256)]
        [DataMember]
        public string ApplicationPath { get; set; }
    	[StringLength(256)]
        [DataMember]
        public string ApplicationVirtualPath { get; set; }
    	[StringLength(256)]
    	[Required]
        [DataMember]
        public string MachineName { get; set; }
    	[StringLength(1024)]
        [DataMember]
        public string RequestUrl { get; set; }
    	[StringLength(256)]
        [DataMember]
        public string ExceptionType { get; set; }
    	[StringLength(8000)]
        [DataMember]
        public string Details { get; set; }
    }
    
}
