//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class Features_Bugs
    {
        [DataMember]
        public int ID { get; set; }
    	[StringLength(50)]
    	[Required]
        [DataMember]
        public string Name { get; set; }
    	[StringLength(100)]
    	[Required]
        [DataMember]
        public string Description { get; set; }
    	[StringLength(50)]
    	[Required]
        [DataMember]
        public string Type { get; set; }
    	[StringLength(50)]
    	[Required]
        [DataMember]
        public string Status { get; set; }
    	[StringLength(50)]
        [DataMember]
        public string Comments { get; set; }
        [DataMember]
        public Nullable<System.Guid> DeveloperAssigned { get; set; }
    	[Required]
        [DataMember]
        public int SprintId { get; set; }
    
        [DataMember]
        public virtual Sprint Sprint { get; set; }
        [DataMember]
        public virtual Sprint Sprint1 { get; set; }
    }
    
}
