//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class PermissionCategory
    {
        public PermissionCategory()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        [DataMember]
        public int ID { get; set; }
    	[StringLength(100)]
    	[Required]
        [DataMember]
        public string Name { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
    
}
