//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class Sprint
    {
        public Sprint()
        {
            this.Features_Bugs = new HashSet<Features_Bugs>();
            this.Features_Bugs1 = new HashSet<Features_Bugs>();
        }
    
        [DataMember]
        public int ID { get; set; }
    	[StringLength(50)]
        [DataMember]
        public string Name { get; set; }
    	[StringLength(50)]
        [DataMember]
        public string Type { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FinishDate { get; set; }
    	[StringLength(50)]
        [DataMember]
        public string Status { get; set; }
        [DataMember]
        public Nullable<System.DateTime> StartDate { get; set; }
    	[Required]
        [DataMember]
        public int ReleaseBacklogID { get; set; }
    
        public virtual ICollection<Features_Bugs> Features_Bugs { get; set; }
        public virtual ICollection<Features_Bugs> Features_Bugs1 { get; set; }
        [DataMember]
        public virtual ReleaseBacklog ReleaseBacklog { get; set; }
    }
    
}
