//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Capstone.Infrastructure.Data.EF.Entities
{
    [DataContract(IsReference=true)]
    public partial class UserProjectPermission
    {
        [DataMember]
        public int ID { get; set; }
    	[Required]
        [DataMember]
        public int ProjectId { get; set; }
    	[Required]
        [DataMember]
        public int PermissionId { get; set; }
    	[Required]
        [DataMember]
        public System.Guid UserId { get; set; }
    
        [DataMember]
        public virtual aspnet_Users aspnet_Users { get; set; }
        [DataMember]
        public virtual Permission Permission { get; set; }
        [DataMember]
        public virtual Project Project { get; set; }
    }
    
}
