// --------------------------------------------
// <auto-generated>
//	  This code was generated from a template
// </auto-generated>
// --------------------------------------------

using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Capstone.Infrastructure.Data.EF.Entities;
using Capstone.Infrastructure.Data.Interface;
using Capstone.Infrastructure.Data.EF;

namespace Capstone.Infrastructure.Data.Repositories {
    public partial class aspnet_PersonalizationPerUserRepository : BaseRepository<aspnet_PersonalizationPerUser>, Iaspnet_PersonalizationPerUserRepository {
    	
    	public aspnet_PersonalizationPerUserRepository(IUnitOfWork _uow) : base(_uow) {
    	}
    }
}
